### ISSUE TITLE
Different Z-axis range handled in Y-axis than X-axis for raster plot

### ISSUE THREAD

**Issue by KevinPoole** [LGSInnovations/sigplot#107]
**Describe the bug**
I am exploring the raster (2D) static plot as an option for a project I am working on. I will be plotting a 64x64 grid of values. I began by plotting a random set of 64x64 values ([see this fiddle](https://jsfiddle.net/jc3n1arf/)) and that looked great. Then, I attempted to plot columns of fixed values, for example:
```
[
    [0,1,2,3,...,61,62,63],
    [0,1,2,3,...,61,62,63],
    [0,1,2,3,...,61,62,63],
    ...
    [0,1,2,3,...,61,62,63],
    [0,1,2,3,...,61,62,63],
    [0,1,2,3,...,61,62,63],
]
```
and this too produced the expected result ([see this fiddle](https://jsfiddle.net/jc3n1arf/1/)). For some reason though, when I plot rows of fixed values such as:
 ```
[
    [0,0,0,0,...,0,0,0],
    [1,1,1,1,...,1,1,1],
    [2,2,2,2,...,2,2,2],
    ...
    [61,61,61,61,...,61,61,61],
    [62,62,62,62,...,62,62,62],
    [63,63,63,63,...,63,63,063
]
```
this does not yield the expected result. I would expect a steady gradient from top to bottom (basically a rotated version of the prior one) but instead I get a steady gradient for about ~15 rows, followed by ~48 (the remaining) rows being displayed at "max" value color ([see this fiddle](https://jsfiddle.net/jc3n1arf/2/))

I can not figure out what would cause this. Any guidance would be greatly appreciated! Great tool!

**Comment by mrecachinas** [comment]
Hi @KevinPoole! Thanks for filing this! In the current behavior of SigPlot, the autoscaling logic only looks at the first 16 lines by default (i.e., in the LPB setting). Note that you can alternatively force a Zmin and Zmax and not use autoscaling.

Let @maihde or me know if you have any further questions.

**Comment by KevinPoole** [comment]
@mrecachinas you were exactly correct! I forced Zmin and Zmax and then I got the behavior I expected. Thanks so much for the quick reply, and late on a Saturday no less!

I have the update jsfiddle here just for completeness sake: https://jsfiddle.net/vjantkpb/
