### ISSUE TITLE
Problem with displaying specs when axes toggled off and on

### ISSUE THREAD

**Issue by sterre** [LGSInnovations/sigplot#22]
We ran into a problem some time ago related to the display of specs. It's been long enough that we lost some of the details, but we think it was something like: turn off both axes, then back on again, and the specs area disappears. 

This patch against a built sigplot-debug.js fixed the issue for us:
[sigplot-debug.js.show_specs.patch.gz](https://github.com/LGSInnovations/sigplot/files/2202983/sigplot-debug.js.show_specs.patch.gz)

The patch just factors the check for `show_readout` separately from `(Gx.pan && !Gx.no_legend_button)` .

**Comment by maihde** [comment]
@sterre sorry for the long delay on this.  I think the `Gx.pan` should simply be removed from that clause entirely.  I have made a fix and it appears to resolve the issue.

**Comment by mrecachinas** [comment]
Fixed in #64.
