### ISSUE TITLE
Want to be able to change raster compression with change_settings

### ISSUE THREAD

**Issue by sterre** [LGSInnovations/sigplot#23]
You can specify `xcmp` to a raster on construction, but not with `change_settings`. You have to reach in to `Gx_.xcompression` to change it programmatically at run time. I'd like to be able to change this while the raster is running to reveal or highlight features as needed by the contents.

Ideally, this would also be available from the MM menu. (It may be, but just masked by the fact that my SigPlot instance is only 200 px  high, so menus are truncated.)

I think we had gotten something related to this into the 1.4 series, but I don't see it in current master.

**Comment by maihde** [comment]
@sterre I just pushed up changes that allows both `change_settings({xcmp: val})` to be used.  Also, added XCompression as a menu item under Traces (for now) but might move it to another location.
