### ISSUE TITLE
Question on installing 2.0.0 RC9 and above

### ISSUE THREAD

**Issue by kmun** [LGSInnovations/sigplot#67]
**Describe the bug**
Trying to update from 2.0.0. RC7 which does not have spin.js , but references it, want to know if there are other files/packages required by sigplot that aren't included in the tzg or zip.   

**To Reproduce**

No steps.  The new version of sigplot.js doesn't run because it can't find spin.   Looking at the baselines in GIT spin.js doesn't appear to be part of the baselines RC9 and above; wondering where it is not found.

**Comment by maihde** [comment]
@kmun 

The distribution model for SigPlot 2.X is different.  In SigPlot 1.X _all_ of the dependencies were manually included in the repository and the final build output was committed to the `dist` folder (for `bower` support).

Given that NPM is now widely available, SigPlot 2.X pulls all of it's dependencies from NPM.

You have a couple of choices if you want everything pre-packaged.

1) Download the published NPM package using this command:

```
npm pack sigplot
```

This will download sigplot-2.0.0-rc14.tgz which has pre-built `dist/sigplot-debug.js` and dist/sigplot-minimized.js' files.

2) If you have checkout of the repository, you can build your own 'dist' output by following the steps in CONTRIBUTING.md, in short:

```
npm install # fetches all the dependencies into node_modules
grunt dist # builds the output files in the dist folder
```

Note, if you use approach (2) you can copy the entire folder (including the `node_modules`) onto a disconnected network and `grunt dist` will still work.

**Comment by mrecachinas** [comment]
Closing this as subsequent issues indicate this solved the issue. @kmun if it didn't solve your issue, feel free to re-open this issue again.
