### ISSUE TITLE
unable to plot FFT 

### ISSUE THREAD

**Issue by DinhH** [LGSInnovations/sigplot#77]
I have a type 1000 bluefile, when I use fft_plot.overlay_href("filename", null, {name: "FFT"}); it doesn't plot correctly. I tried to look at the sample file at http://demo.axiosengineering.com/sigplot/assets/dat/fsk_fft.tmp it doesn't exsist. I was hopeping to see the structure of that file.

**Comment by maihde** [comment]
@DinhH that URL is no longer active.

Here is a JSFiddle that shows how to use `overlay_href`

https://jsfiddle.net/v3khm240/1/

Let me know if this helps.

**Comment by DinhH** [comment]
That helps a lot!
Do you know where I can find more detail on the format of the bluefile for FFT? Because it seems like the one I have doesn't work with sigplot.
Thanks

**Comment by maihde** [comment]
The bluefile format for `fsk_fft.tmp` is just a standard bluefile.

You can use code like this to see what the header looks like
```
reader = new sigplot.bluefile.BlueFileReader();
reader.read_http("https://sigplot.lgsinnovations.com/dat/fsk_fft.tmp", function(header) {
    console.log(header)
});
```

Which for my file looks like this:

```
ape: 1
​bpa: 4
​bpe: 4
​bps: 4
​class: 1
​data_size: 131072
​data_start: 512
​datarep: "EEEI"
​ext_size: 0
​ext_start: 0
​file_name: "fsk_fft.tmp"
​format: "SF"
​headrep: "EEEI"
​options: Object { ext_header_type: "dict" }
​size: 32768
​spa: 1
​subsize: 1
​timecode: 0
​type: 1000
​version: "BLUE"
​xdelta: 15.2587890625
​xstart: -0
​xunits: 3
yunits: 1
```

Can you run this same code on your file and provide me with the output, or alternative, provide me with a copy of your file?

Another thing to be aware of, if you are doing your development using 'file:///' URLs for your webpage you will not be able to load bluefiles via HREF due to browser security restrictions.  Have you looked in the browser Developer Console to see if there are any errors being reported?

**Comment by DinhH** [comment]
Everything looks the same, the only thing that caught my attention is the format. Mine is "CF". Does that play a role?

**Comment by maihde** [comment]
Nope, CF is fine.  For example, see this JSFiddle where I plot a CF file instead.

https://jsfiddle.net/u4zfjrkq/

If you can provide a copy of your bluefile that would really help in figuring out what's going on.

**Comment by DinhH** [comment]
I don't have permission to send you the bluefile. but I think I have figured it out. The bluefile I have been using isn't fft specific it is just a fd data. 

Thanks for all of your help!

**Comment by maihde** [comment]
@DinhH SigPlot isn't FFT specific either, so the data should plot regardless.  If you cannot send me the file, I recommend you send it to @mrecachinas since he works in the same company as you.

**Comment by maihde** [comment]
@DinhH ...did you solve your issue?  Was @mrecachinas able to help?

**Comment by mrecachinas** [comment]
It's been a few months with no response, so I'm going to close this issue. @DinhH if you're having anymore issues, please re-open or submit a new issue!
